---
#
#  Add swapfile per Jetson Nano DLI setup instructions.  Not recommended on a
#  32 GB (or smaller) SD card.
#
- name: "create swap - disable nvzramconfig"
  systemd:
    name: nvzramconfig
    enabled: no
  when: swapsize_gb > 0
  tags:
    - swap

- name: "check if swap file exists"
  stat:
    path: "/mnt/{{ swapsize_gb }}GB.swap"
  register: st
  when: swapsize_gb > 0
  tags:
    - swap

- name: "create swap file if not exists"
  command: "fallocate -l {{ swapsize_gb }}G /mnt/{{ swapsize_gb }}GB.swap"
  when: swapsize_gb > 0 and st.stat.islnk is not defined
  tags:
    - swap

- name: "verify permission on swap file"
  file: 
    path: "/mnt/{{ swapsize_gb }}GB.swap"
    owner: root
    group: root
    mode: 0600
  when: swapsize_gb > 0
  tags:
    - swap

- name: "register swap file"
  command: "mkswap /mnt/{{ swapsize_gb }}GB.swap"
  when: swapsize_gb > 0 and st.stat.islnk is not defined
  tags:
    - swap

- name: "verify swap will mount"
  mount:
    src: "/mnt/{{ swapsize_gb }}GB.swap"
    opts: defaults
    state: present
    fstype: swap
    path: swap
  when: swapsize_gb > 0
  tags:
    - swap

- name: "mount swap"
  command: "swapon /mnt/{{ swapsize_gb }}GB.swap"
  when: swapsize_gb > 0 and st.stat.islnk is not defined
  tags:
    - swap


