---

# Handle boot and autologin settings
- name: enable cli only
  command: "raspi-config nonint do_boot_behaviour B1"
  when: not macaddrs[my_macaddr].enable_gui and not macaddrs[my_macaddr].enable_autologin and (raspi_gui_enabled or raspi_autologin_enabled)

- name: enable cli with autologin
  command: "raspi-config nonint do_boot_behaviour B2"
  when: not macaddrs[my_macaddr].enable_gui and macaddrs[my_macaddr].enable_autologin and (raspi_gui_enabled or not raspi_autologin_enabled)

- name: enable desktop gui
  command: "raspi-config nonint do_boot_behaviour B3"
  when: macaddrs[my_macaddr].enable_gui and not macaddrs[my_macaddr].enable_autologin and (not raspi_gui_enabled or raspi_autologin_enabled)

- name: enable desktop gui with autologin
  command: "raspi-config nonint do_boot_behaviour B4"
  when: macaddrs[my_macaddr].enable_gui and macaddrs[my_macaddr].enable_autologin and (not raspi_gui_enabled or raspi_autologin_enabled)

#- name: set bootwait option
#  command: "raspi-config nonint do_boot_wait {{ not macaddrs[my_macaddr].raspi_bootwait }}"
#when: macaddrs[my_macaddr].raspi_boot_nowait
