---
- name: get Raspberry Pi model type
  shell: "raspi-config nonint get_pi_type"
  register: raspi_type
  changed_when: False

- name: get hostname via raspi-config
  shell: "raspi-config nonint get_hostname"
  register: raspi_hostname
  changed_when: False

- name: get boot-to-gui setting 
  shell: "raspi-config nonint get_boot_cli" # 0 == "boot to cli"; 1 == "boot to gui"
  register: raspi_boot_gui
  changed_when: False

- name: get autologin setting
  shell: "raspi-config nonint get_autologin" # 0 == "enable autologin"; 1 == "disable autologin"
  register: raspi_noautologin
  changed_when: False

- name: get wait-for-network-on-boot setting 
  shell: "raspi-config nonint get_boot_wait" # 0 == "wait"; 1 == "don't wait"
  register: raspi_boot_nowait
  changed_when: False

- name: get wifi country
  shell: "raspi-config nonint get_wifi_country"
  register: raspi_wifi_country
  changed_when: False

- name: get camera status
  shell: "raspi-config nonint get_camera" # 0 == "camera enabled"; 1 == "camera disabled"
  register: raspi_camera_disabled
  changed_when: False

- name: get ssh enabled status
  shell: "raspi-config nonint get_ssh"
  register: raspi_ssh_disabled
  changed_when: False

- name: get VNC enabled status
  shell: "raspi-config nonint get_vnc"
  register: raspi_vnc_disabled
  changed_when: False

- name: get SPI enabled status
  shell: "raspi-config nonint get_spi"
  register: raspi_spi_disabled
  changed_when: False

- name: get I2C enabled status
  shell: "raspi-config nonint get_i2c"
  register: raspi_i2c_disabled
  changed_when: False

- name: get serial enabled status
  shell: "raspi-config nonint get_serial"
  register: raspi_serial_disabled
  changed_when: False

- name: get hardware serial enabled status
  shell: "raspi-config nonint get_serial_hw"
  register: raspi_serial_hw_disabled
  changed_when: False

- name: get onewire enabled status
  shell: "raspi-config nonint get_onewire"
  register: raspi_onewire_disabled
  changed_when: False

- name: get remote gpio enabled status
  shell: "raspi-config nonint get_rgpio"
  register: raspi_rgpio_disabled
  changed_when: False

- name: get overclock state 
  shell: "raspi-config nonint get_config_var arm_freq /boot/config.txt"
  register: raspi_overclock
  changed_when: False

- name: get fs expandability
  shell: "raspi-config nonint get_can_expand"
  register: raspi_fs_unexpandable
  changed_when: False

- name: get overscan setting
  shell: "raspi-config nonint get_overscan"
  register: raspi_overscan
  changed_when: False

- name: get GPU memory split
  shell: "raspi-config nonint get_config_var gpu_mem /boot/config.txt"
  register: raspi_gpu_mem
  changed_when: False

- name: get GPU memory split 256
  shell: "raspi-config nonint get_config_var gpu_mem_256 /boot/config.txt"
  register: raspi_gpu_mem_256
  changed_when: False

- name: get GPU memory split 512
  shell: "raspi-config nonint get_config_var gpu_mem_512 /boot/config.txt"
  register: raspi_gpu_mem_512
  changed_when: False

- name: get GPU memory split 1024
  shell: "raspi-config nonint get_config_var gpu_mem_1024 /boot/config.txt"
  register: raspi_gpu_mem_1024
  changed_when: False

- name: set raspi-config facts
  set_fact:
    raspi_type: raspi_type.stdout
    raspi_hostname: raspi_hostname.stdout
    raspi_boot_gui: raspi_boot_gui.stdout
    raspi_noautologin: raspi_noautologin.stdout
    raspi_boot_nowait: raspi_boot_nowait.stdout
    raspi_wifi_country: raspi_wifi_country.stdout
    raspi_camera_disabled: raspi_camera_disabled.stdout
    raspi_ssh_disabled: raspi_ssh_disabled.stdout
    raspi_vnc_disabled: raspi_vnc_disabled.stdout
    raspi_spi_disabled: raspi_spi_disabled.stdout
    raspi_i2c_disabled: raspi_i2c_disabled.stdout
    raspi_serial_disabled: raspi_serial_disabled.stdout
    raspi_serial_hw_disabled: raspi_serial_hw_disabled.stdout
    raspi_onewire_disabled: raspi_onewire_disabled.stdout
    raspi_rpgio_disabled: raspi_rpgio_disabled.stdout
    raspi_overclock: raspi_overclock.stdout
    raspi_fs_unexpandable: raspi_fs_unexpandable.stdout
    raspi_overscan: raspi_overscan.stdout
    raspi_gpu_mem: raspi_gpu_mem.stdout
    raspi_gpu_mem_256: raspi_gpu_mem_256.stdout
    raspi_gpu_mem_512: raspi_gpu_mem_512.stdout
    raspi_gpu_mem_1024: raspi_gpu_mem_1024.stdout
